package cs5004.animator.controller;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;

import cs5004.animator.model.IModel;
import cs5004.animator.model.IShape;
import cs5004.animator.model.ViewShape;
import cs5004.animator.view.IView;

/**
 * Created by vidojemihajlovikj on 7/31/19.
 */
public class AnimationController implements IController {
  IView view;
  IModel model;
  Timer timer;
  int currentFrame;

  /**
   * This is a controller provided by VIdo to run our animator.
   *
   * @param view  - our current view, animation.
   * @param model - our model that is generated by our builder class.
   */
  public AnimationController(IView view, IModel model) {
    this.view = view;
    this.model = model;
    currentFrame = 0;
    timer = new Timer(20, new ActionListener() {
      //TODO: actually implement this timer
      @Override
      public void actionPerformed(ActionEvent e) {

        //
        //viewshape or IShape?
        java.util.List<ViewShape> viewShapes =
                new java.util.ArrayList<>();

        //is viewShape even needed?
        for (IShape modelShape : model.getAllShapesAtFrame(currentFrame)) {
          ViewShape convertedShape = new ViewShape(modelShape);
          //System.out.println(convertedShape.getX());
          //System.out.println(convertedShape.getY());
          viewShapes.add(convertedShape);
        }
        //model.getAllShapesAtFrame(currentFrame);

        view.renderList(viewShapes);
        currentFrame++;

        //System.out.println("firing away");
      }
    });

  }

  /**
   * runs our program.
   */
  @Override
  public void run() {
    timer.start();
    //model.getAllShapesAtFrame(currentFrame);
  }

  /**
   * sets the controller to a new variable.
   *
   * @return a new controller.
   */
  @Override
  public Controller setController() {
    return null;
  }
}
